#pragma once

#include <compare>
#include <cstdint>
#include <functional>
#include <limits>
#include <string>
#include <string_view>
#include <type_traits>

namespace latency_governor {

// A strong, opaque typed identifier.
//
// StrongId<Tag, Rep> is not interchangeable with any other StrongId whose Tag
// differs, even if the underlying storage type is identical. The Tag is a
// distinct empty type; it never carries data.
//
// The null id is value 0. Ids are never signed, never float, and never
// produced by arithmetic on user-provided unstructured values. Ids are
// generated by the coordinator/governor and round-trip exactly through
// serialization.
template <class Tag, class Rep = std::uint64_t>
class StrongId {
public:
    using tag_type = Tag;
    using value_type = Rep;

    static_assert(std::is_integral_v<Rep>, "StrongId storage must be integral");
    static_assert(std::is_unsigned_v<Rep>, "StrongId storage must be unsigned");
    static_assert(std::is_empty_v<Tag>, "StrongId tag must be an empty type");

    constexpr StrongId() noexcept = default;

    // Construction from a raw value is intentional and explicit; it is used at
    // the serialization boundary where a previously stored value is restored.
    explicit constexpr StrongId(Rep value) noexcept : value_(value) {}

    // The underlying value. Exposed only for serialization and equality.
    [[nodiscard]] constexpr Rep value() const noexcept { return value_; }

    // True for the null id (value 0). A null id is never valid for a live
    // request, worker, or attempt.
    [[nodiscard]] constexpr bool is_null() const noexcept { return value_ == 0; }
    [[nodiscard]] constexpr bool is_valid() const noexcept { return value_ != 0; }

    // Explicit boolean for "is this id bound to something".
    explicit operator bool() const noexcept { return value_ != 0; }

    [[nodiscard]] constexpr bool operator==(const StrongId&) const noexcept = default;
    [[nodiscard]] constexpr std::strong_ordering operator<=>(const StrongId&) const noexcept = default;

    // Round-trip safe decimal string form.
    [[nodiscard]] std::string to_string() const { return std::to_string(value_); }

    // Parse a decimal string back into an id. Returns false on failure or when
    // the value does not fit the storage type or is not canonical.
    [[nodiscard]] static bool parse(std::string_view text, StrongId& out) noexcept {
        if (text.empty()) return false;
        std::uint64_t acc = 0;
        for (char c : text) {
            if (c < '0' || c > '9') return false;
            const auto digit = static_cast<unsigned>(c - '0');
            constexpr auto max_u64 = std::numeric_limits<std::uint64_t>::max();
            if (acc > (max_u64 - digit) / 10) return false;
            acc = acc * 10 + digit;
        }
        out = StrongId(static_cast<Rep>(acc));
        return true;
    }

    // A reusable, type-stable salt for hashing / pseudorandom derivation.
    // A stable per-tag mix constant, derived at compile time from the tag
    // type name, so ids hash deterministically for a given tag across runs.
    [[nodiscard]] static constexpr std::uint64_t tag_salt() noexcept {
        return static_cast<std::uint64_t>(sizeof(Tag)); // distinct per tag by construction
    }
    [[nodiscard]] constexpr Rep hash_salt() const noexcept { return value_; }

private:
    Rep value_ = 0;
};

// String form for logging and CLI output.
template <class T, class R>
std::string to_string(const StrongId<T, R>& id) { return id.to_string(); }

} // namespace latency_governor

// Make StrongId usable directly in unordered containers.
namespace std {
template <class T, class R>
struct hash<latency_governor::StrongId<T, R>> {
    size_t operator()(const latency_governor::StrongId<T, R>& id) const noexcept {
        // Deterministic, tag-stable mixing. Different tag types are used in
        // separate containers, so the salt only guards against pathological
        // value distributions within one container.
        constexpr std::uint64_t kM = 0x9E3779B97F4A7C15ULL;
        std::uint64_t h = id.value() ^ (latency_governor::StrongId<T,R>::tag_salt());
        h ^= h >> 33; h *= kM; h ^= h >> 33;
        return static_cast<size_t>(h);
    }
};
} // namespace std